spring.application.name=bank
spring.profiles.active=${SPRING_PROFILES_ACTIVE:h2}

spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
